# Generated by Django 4.1.2 on 2022-10-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post_img/default.jpg', upload_to='post_img/'),
        ),
    ]
